services:
  loki:
    image: grafana/loki:latest
    container_name: loki
    command: -config.file=/etc/loki/local-config.yaml -validation.allow-structured-metadata=false
    networks:
      - grafana-network
    ports: 
      - '3100:3100'

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - '9090:3000'
    environment:
      #Sugestão de colocar nas variáveis de ambiente
      - GF_SECURITY_ADMIN_USER=${GF_SECURITY_ADMIN_USER}
      - GF_SECURITY_ADMIN_PASSWORD=${GF_SECURITY_ADMIN_PASSWORD}
    depends_on:
      - loki
    networks:
      - grafana-network

networks:
  grafana-network:
    external: true